name: signup

on:
    push:
        branches:
            - master
    schedule:
        - cron: "5 00 * * *"
jobs:
    start_sign:
        name: start_daily_sign
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: checkout_submodules
              uses: textbook/git-checkout-submodule-action@master
            - uses: actions/setup-node@v2-beta
              with:
                node-version: '14'
            - name: Sign southplus
              shell: bash
              env:
                LINE_USERID: ${{ secrets.LINE_USERID }}
                LINECHANNEL: ${{ secrets.LINECHANNEL }}
                LINESECRET: ${{ secrets.LINESECRET }}
                LINECHANNELTOKEN: ${{ secrets.LINECHANNELTOKEN }}
                COOKIE: ${{ secrets.COOKIE }}
              run: |
                echo "Install Dependencies"
                npm i
                echo "Build Script"
                npm run build
                echo "Run Signup"
                npm run signup
